name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: test
      uses: actions/checkout@v1
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        checkout: false
        documentation_path: docs/source
        requirements_path: docs/source/requirements.txt
